# Generated by Django 6.0.6 on 2026-07-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('modern', 'Modern'), ('contemporary', 'Contemporary'), ('traditional', 'Traditional'), ('minimalist', 'Minimalist'), ('luxury', 'Luxury'), ('scandinavian', 'Scandinavian'), ('industrial', 'Industrial')], default='modern', max_length=50)),
                ('room_type', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('full_home', 'Full Home'), ('office', 'Office'), ('exterior', 'Exterior')], default='full_home', max_length=50)),
                ('budget_range', models.CharField(blank=True, choices=[('under_5l', 'Under ₹5 Lakhs'), ('5l_10l', '₹5L – ₹10L'), ('10l_20l', '₹10L – ₹20L'), ('20l_50l', '₹20L – ₹50L'), ('above_50l', 'Above ₹50 Lakhs')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
