# Generated by Django 6.0.6 on 2026-07-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
