# Generated by Django 6.0.6 on 2026-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('bhk_type', models.CharField(blank=True, choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('villa', 'Villa / Independent House'), ('office', 'Office Space'), ('other', 'Other')], max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('under_5l', 'Under ₹5 Lakhs'), ('5l_10l', '₹5L – ₹10L'), ('10l_20l', '₹10L – ₹20L'), ('20l_50l', '₹20L – ₹50L'), ('above_50l', 'Above ₹50 Lakhs')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, help_text='URL or page name where lead came from', max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
